# Generated by Django 5.0.7 on 2024-08-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attendence_student_attendence_teacher_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='attendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
