# Generated by Django 5.0.7 on 2024-08-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_name_remove_student_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendence',
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
