# Generated by Django 5.0.7 on 2024-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_task_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='binary_data',
            field=models.BinaryField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='binary_data',
            field=models.BinaryField(default=False),
        ),
    ]
