# urls.py
from django.urls import path
from .import views

urlpatterns = [

    path('register', views.register, name='register'),
    path('register_', views.register_, name='register_'),
    path('contact', views.contact, name='contact'),
    path('erh', views.page4, name='page4'),
    path('', views.home, name='home'),
    path('login', views.loginpage, name='loginpage'),
    path('login_view', views.login_view, name='login_view'),
    path('adminmod',views.adminmod,name='adminmod'),
    path('student_dashboard',views.student_dashboard,name='student_dashboard'),
    path('teacher_dashboard',views.teacher_dashboard,name='teacher_dashboard'),
    path('lgout',views.lgout,name='lgout'),
    path('add_course_', views.add_course_, name='add_course_'),
    path('aboutus', views.aboutus, name='aboutus'),
    path('add_course', views.add_course, name='add_course'),
    path('course_list', views.course_list, name='course_list'),
    path('edit_course/<int:course_id>', views.edit_course, name='edit_course'),
    path('delete_course/<int:course_id>', views.delete_course, name='delete_course'),
    path('edit_course_/<int:course_id>', views.edit_course_, name='edit_course_'),
    path('delete_course_/<int:course_id>', views.delete_course_, name='delete_course_'),
    path('list_fresh_users/', views.list_fresh_users, name='list_fresh_users'),
    path('approve_user/<str:user_type>/<int:user_id>/', views.approve_user, name='approve_user'),
    path('list_new_users/', views.list_new_users, name='list_new_users'),
    path('assign_course/<str:user_type>/<int:user_id>/', views.assign_course, name='assign_course'),
    path('assign_course_/<str:user_type>/<int:user_id>/', views.assign_course_, name='assign_course_'),
    path('confirm_delete_user/<str:user_type>/<int:user_id>/', views.confirm_delete_user, name='confirm_delete_user'),
    path('delete_user/<str:user_type>/<int:user_id>/', views.delete_user, name='delete_user'),
    path('users_by_course/', views.users_by_course, name='users_by_course'),
    path('delete_user_from_course/<str:user_type>/<int:user_id>/', views.delete_user_from_course, name='delete_user_from_course'),
    path('tenter_attendance/', views.tenter_attendance, name='tenter_attendance'),
    path('t_enter_attendance/', views.t_enter_attendance, name='t_enter_attendance'),
    path('tattendance_report/', views.tattendance_report, name='tattendance_report'),
    path('t_attendance_report/', views.t_attendance_report, name='t_attendance_report'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password_/', views.reset_password_, name='reset_password_'),
    path('tstudents_list/', views.tstudents_list, name='tstudents_list'),
    path('tadd_task/', views.tadd_task, name='tadd_task'),
    path('tadd_task_/', views.tadd_task_, name='tadd_task_'),
    path('ttask_list/', views.ttask_list, name='ttask_list'),
    path('senter_attendance/', views.senter_attendance, name='senter_attendance'),
    path('s_enter_attendance/', views.s_enter_attendance, name='s_enter_attendance'),
    path('sattendance_report/', views.sattendance_report, name='sattendance_report'),
    path('s_attendance_report/', views.s_attendance_report, name='s_attendance_report'),
    path('asattendance_report/', views.asattendance_report, name='asattendance_report'),
    path('as_attendance_report/', views.as_attendance_report, name='as_attendance_report'),
    path('student_task_list/', views.student_task_list, name='student_task_list'),
    path('add_task/add/<int:task_id>/', views.add_task, name='add_task'),
    path('add_task_/add/<int:task_id>/', views.add_task_, name='add_task_'),
    path('attendance_summary/', views.attendance_summary, name='attendance_summary'),
    path('attendance_summary_/', views.attendance_summary_, name='attendance_summary_'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('edit_student_profile/edit/', views.edit_student_profile, name='edit_student_profile'),
    path('profile/edit_/', views.edit_student_profile_, name='edit_student_profile_'),
    path('teacher_task_list/', views.teacher_task_list, name='teacher_task_list'),
    path('teacher_attendance/', views.teacher_attendance_summary, name='teacher_attendance_summary'),
    path('teacher_attendance_dates/', views.teacher_attendance_summary_with_dates, name='teacher_attendance_summary_with_dates'),
    path('view_profile/<str:user_type>/<int:user_id>/', views.view_profile, name='view_profile'),
    path('tstudent_profile/<int:student_id>/', views.tstudent_profile, name='tstudent_profile'),
    path('teacher_profile/', views.teacher_profile, name='teacher_profile'),
    path('edit_teacher_profile/edit/', views.edit_teacher_profile, name='edit_teacher_profile'),
    path('edit_teacher_profile_/edit_/', views.edit_teacher_profile_, name='edit_teacher_profile_'),
    path('student_tasks/', views.student_tasks, name='student_tasks'),
    path('tdelete_task/<int:task_id>', views.tdelete_task, name='tdelete_task'),
    

]
